import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Skill } from '../entities/skill';

@Injectable({
  providedIn: 'root',
})
export class SkillService {

  public getSkills(): Observable<Skill[]> {
    return of(this.skills);
  }

  private skills = [
    new Skill(1, '+1 acción', 'El superviviente tiene una acción adicional que puede utilizar como desee.'),
    new Skill(2, '+1 acción de [tipo] gratuita', 'El superviviente tiene 1 acción adicional del tipo especificado (combate, cuerpo a cuerpo, a distancia, movimiento o búsqueda). Esta acción sólo puede ser utilizada para llevar a cabo una acción de ese tipo.'),
    new Skill(3, '+1 al Alcance máximo', 'El alcance máximo del superviviente con armas a distancia aumenta en 1.'),
    new Skill(4, '+1 al Daño: [Acción]', 'El superviviente obtiene una bonificación de +1 al daño con el tipo de acción especificado (combate, cuerpo a cuerpo o a distancia).'),
    new Skill(5, '+1 a las tiradas: [Acción]', 'El superviviente suma 1 al resultado de cada dado que lance en una acción del tipo especificado (combate, cuerpo a cuerpo o distancia). El resultado máximo siempre es 6'),
    new Skill(6, '+1 dado: [Acción]', 'El superviviente lanza un dado adicional con sus armas al realizar acciones del tipo especificado (combate, cuerpo a cuerpo o a distancia). Las armas dobles reciben un dado cada una, para un total de +2 dados por cada acción de combate con armas dobles del tipo especificado.'),
    new Skill(7, '+1 Zona por movimiento', 'Cuando el superviviente gasta 1 acción para moverse, puede recorrer 1 o 2 Zonas en lugar de 1 sola. Entrar en una zona que contenga zombis termina la acción de movimiento del superviviente.'),
    new Skill(8, '2 cócteles son mejores que 1', 'Cada vez que el superviviente descarte un Cóctel molotov para efectuar una acción de combate a distancia, lanza un dado. Si obtienes 4 o más, la carta del cóctel molotov puede ponerse en la mochila del superviviente sin coste alguno. El resultado de este dado no puede alterarse ni repetirse de ningún modo.'),
    new Skill(9, '6 en el dado: +1 al daño [Acción]', 'Suma 1 al daño del arma que utilice el superviviente por cada 6 que obtenga al realizar una acción del tipo especificado (combate, cuerpo a cuerpo o a distancia). Los efectos de juego que permitan volver a lanzar dados deben aplicarse antes de determinar la bonificación al daño conferida por esta habilidad.'),
    new Skill(10, '6 en el dado: +1 dado de [Acción]', 'Puede lanzarse un dado adicional por cada 6 obtenido en una acción del tipo especificado (combate, cuerpo a cuerpo o a distancia). El jugador seguirá tirando dados mientras obtenga un 6 en ellos. Los efectos de juego que permitan volver a lanzar los dados deben aplicarse antes de lanzar los dados adicionales conferidos por esta habilidad.'),
    new Skill(11, 'A mano', 'Todas las cartas de equipo que estén en el inventario del superviviente se consideran equipadas en sus manos.'),
    new Skill(12, '[Acción]: Daño 2', 'Las armas del tipo especificado (combate, cuerpo a cuerpo o a distancia) que utilice el superviviente y cuyo daño sea 1 se consideran de daño 2.'),
    new Skill(13, 'Acometida', 'El superviviente puede utilizar esta habilidad sin coste alguno una vez en cada uno de sus turnos. Se moverá 1 máximo de 2 zonas hasta una zona que contenga al menos 1 zombi. Las reglas normales de movimiento se siguen aplicando. Entrar en una zona que contenga zombis termina la acción de movimiento del superviviente.'),
    new Skill(14, 'Acorazado: [Tipo de zombi]', 'El superviviente ignora todas las Heridas que provengan del tipo de zombi especificado (por ejemplo, <<Acorazado: Caminante>> protegería contra todos los Caminantes).'),
    new Skill(15, 'Afortunado', 'Por cada acción que realice el superviviente, su jugador puede volver a lanzar una vez más todos los dados. El nuevo resultado sustituye al anterior. Esta habilidad se acumula con los efectos de las cartas de equipo que permiten repetir las tiradas.'),
    new Skill(16, 'Aguanta la respiración', 'El superviviente roba 1 carta de equipo (solamente del mazo de equipo de la caja básica) cada vez que el último zombi de su zona sea eliminado, ya sea por el propio superviviente, por otro superviviente o por algún efecto de juego. Esta habilidad funciona en cualquier zona, incluidas las de calle, y puede utilizarse varias veces en un mismo turno. Esto NO se considera una acción de búsqueda.'),
    new Skill(17, 'Ambidiestro', 'El superviviente trata todas las armas como si tuviesen el símbolo doble.'),
    new Skill(18, 'Arma improvisada: A distancia', 'El superviviente puede utilizar esta habilidad una vez en cada uno de sus turnos para efectuar un ataque a distancia gratuito usando las siguientes puntuaciones de combate. Los demás modificadores al combate a distancia (como los de otras habilidades, por ejemplo) se siguen aplicando.'),
    new Skill(19, 'Arma improvisada: Cuerpo a cuerpo', 'El superviviente puede utilizar esta habilidad una vez en cada uno de sus turnos para efectuar un ataque cuerpo a cuerpo gratuito usando las siguientes puntuaciones de combate. Los demás modificadores al combate cuerpo a cuerpo (como los de otras habilidades, por ejemplo) se siguen aplicando.'),
    new Skill(20, 'Ataque y retirada', 'El superviviente puede utilizar esta habilidad sin ningún coste, justo después de resolver una acción de combate cuerpo a cuerpo o a distancia que resulte en la eliminación de al menos un zombi. A continuación puede efectuar una acción de movimiento gratuita. El superviviente no necesita gastar acciones adicionales para realizar esta acción de movimiento gratuita si hay zombis en su misma zona.'),
    new Skill(21, 'Bárbaro', 'Al resolver una acción de combate cuerpo a cuerpo, el superviviente puede sustituir el valor de dados del arma o armas de combate cuerpo a cuerpo que esté utilizando por el número de zombis que se encuentren en su zona. Las habilidades que afecten al número de dados, como +1 dado: Cuerpo a cuerpo, se siguen aplicando.'),
    new Skill(22, 'Búsqueda: 2 cartas', 'Roba 2 cartas cuando lleves a cabo una acción de búsqueda con el superviviente.'),
    new Skill(23, 'Carga súbita', 'El superviviente puede usar esta habilidad una vez en cada uno de sus turnos. Gastando una acción, puede moverse un máximo de 2 zonas hasta una zona donde haya zombis dentro del alcance de alguna de las armas a distancia que tiene equipadas. a continuación, obtiene 1 acción de combate a distancia gratuita. Se aplican las reglas de movimiento habituales.'),
    new Skill(24, 'Defensa doméstica', 'El superviviente no se ve limitado a alcance 0-1 cuando traza líneas de visión a través de zonas de edificio.'),
    new Skill(25, 'Destino', 'El superviviente puede utilizar esta habilidad una vez por turno, al revelar una carta de equipo que haya robado. Descarta esa carta y roba otra carta de equipo del mismo mazo.'),
    new Skill(26, 'Disparo a bocajarro', 'El superviviente puede efectuar acciones de combate a distancia en su misma zona, sin importar cual sea su alcance mínimo. Cuando dispara a alcance 0, el superviviente elige libremente los blancos y puede matar a cualquier tipo de zombi (sin importar las capacidades especiales que puedan tener). Sus armas a distancia siguen teniendo que infligir el daño necesario para matar a sus objetivos. El fuego amigo se ignora'),
    new Skill(27, 'Distribuidor', 'Al resolver el paso de aparición de la fase de los zombis, roba tantas carta de zombi como el número de zonas de aparición que estén activas. Mira esas cartas, asigna 1 a cada zona de aparición activa y resuelve la aparición de los zombis indicados.'),
    new Skill(28, 'Duro', 'El superviviente ignora la primera herida infligida por un ataque de zombi (en la fase de los zombis) y también debido al fuego amigo (a consecuencia de una acción de combate a distancia efectuada por otro superviviente).'),
    new Skill(29, 'Empieza con 2 PA', 'El superviviente empieza la partida con 2 puntos de adrenalina.'),
    new Skill(30, 'Empieza con X de vida', 'El superviviente empieza la partida con la cantidad indicada de vida. Esta cifra es su puntuación básica de vida.'),
    new Skill(31, 'Empujón', 'El superviviente puede utilizar esta habilidad, sin coste, una vez en cada uno de sus turnos. Selecciona una zona que esté a alcance 1 del superviviente. Ambas zonas deben compartir una ruta despejada. Todos los zombis que se encuentren en la misma zona que el superviviente son desplazados ala zona seleccionada. Esto no es un movimiento.'),
    new Skill(32, 'Ensañamiento: [Acción]', 'El superviviente añade 1 dado a las tiradas de las acciones consecutivas del tipo especificado (combate, cuerpo a cuerpo o a distancia). Esta bonificación es acumulativa y se aplica hasta el final del turno del superviviente. La bonificación se pierde si el superviviente realiza otro tipo de acción.'),
    new Skill(33, 'Escurridizo', 'El superviviente no tiene que gastar acciones adicionales cuando realiza una acción de movimiento para salir de una zona en la que hay zombis. También ignora a los zombis cuando realiza acciones de movimiento (incluidas las que le permiten recorrer varias zonas, como por ejemplo al usar la habilidad Esprintar.)'),
    new Skill(34, '¿Eso es todo lo que tienes?', 'Esta habilidad puede utilizarse cada vez que el superviviente vaya a recibir heridas. Se anula 1 herida por cada carta de equipo que se descarte del inventario del superviviente.'),
    new Skill(35, 'Esprintar', 'El superviviente puede utilizar esta habilidad una vez en cada uno de sus turnos. Gastando una acción de movimiento, el superviviente puede recorrer 2 o 3 zonas en vez de 1. Entrar en una zona que contenga zombis termina la acción de movimiento del superviviente.'),
    new Skill(36, 'Evasión', 'Cada vez que aparezcan zombis a alcance 0-1 (y antes de resolver cualquier posible avance impetuoso), el superviviente puede realizar inmediatamente una acción de movimiento gratuita. No necesita gastar acciones adicionales para llevar a cabo este movimiento aunque haya zombis en su misma zona. El superviviente puede utilizar esta habilidad una vez por cada carta de zombi que se robe.'),
    new Skill(37, 'Experto en armas dobles', 'El superviviente dispone de una acción de combate gratuita mientras tenga equipadas armas dobles. Esta acción solamente puede usarse con las armas equipadas.'),
    new Skill(38, 'Forzar entrada', 'El superviviente no necesita cartas de equipo para abrir puertas. Tampoco hace ruido cuando utiliza esta habilidad. Sin embargo, el resto de requisitos siguen siendo obligatorios (como recoger un determinado objetivo para poder abrir puertas). Por último, el superviviente dispone de una acción adicional que sólo puede usar para abrir puertas.'),
    new Skill(39, 'Francotirador', 'El superviviente puede elegir libremente los blancos de todas sus acciones de combate a distancia. El fuego amigo se ignora.'),
    new Skill(40, 'Fuego automático', 'Al resolver una acción de combate a distancia, el superviviente puede sustituir el número de dados del arma o armas de combate a distancia que esté utilizando por el número de zombis que se encuentren en la zona a la que dispara. Las habilidades que afecten al número de dados, como +1 dado: A distancia, se siguen aplicando.'),
    new Skill(41, 'Hermano de batalla: [Efecto]', 'El superviviente puede usar esta habilidad cada vez que esté en la misma zona que otro superviviente. Mientras permanezca activa, todos los supervivientes de esa zona (incluido el que posee la habilidad) se beneficiarán de la habilidad o efecto de juego indicado. Esta habilidad no se aplica a los acompañantes.'),
    new Skill(42, 'Líder nato', 'Durante el turno del superviviente, éste puede otorgar 1 acción gratuita a otro superviviente, que podrá utilizarla como desee. Esta acción debe utilizarse inmediatamente, luego se reanuda el turno del superviviente que ha usado Líder nato.'),
    new Skill(43, 'Maestro de la espada', 'El superviviente trata todas las armas de combate cuerpo a cuerpo como si tuvieran el símbolo doble.'),
    new Skill(44, 'Mano firme', 'El superviviente puede ignorar a otros supervivientes de su elección cuando falle con una acción de combate a distancia. Esta habilidad no se aplica a los efectos de juego que lo maten todo en una zona (como por ejemplo el Cóctel molotov).'),
    new Skill(45, 'Medicina de campaña', 'El superviviente puede utilizar esta habilidad una vez en cada uno de sus turnos. Gastando 1 acción, puede moverse un máximo de 2 zonas hasta una zona que contenga al menos 1 superviviente. Luego puede curar 1 herida a cualquier superviviente que se encuentre en la zona de destino (incluído el mismo). Se aplican las reglas de movimiento habituales. La medicina de campaña puede usarse incluso aunque ninguno de los supervivientes que estén en la zona de destino haya sufrido heridas.'),
    new Skill(46, 'Médico', 'Esta habilidad se utiliza gratuitamente en cada fase final. El superviviente, así como todos los demás supervivientes que estén en su misma zona, pueden curarse 1 herida (mínimo 0 heridas). El superviviente gana 1PA por cada herida que cure de este modo.'),
    new Skill(47, 'Par conjuntado', 'Cuando el superviviente lleve a cabo una acción de búsqueda y robe una carta de equipo con el símbolo doble, puede buscar inmediatamente una segunda carta del mismo tipo  en el mazo de cartas de equipo y quedarse con ella. Después baraja el mazo.'),
    new Skill(48, 'Pasar desapercibido', 'El superviviente no puede ser golpeado por el fuego amigo (pero los Cócteles molotov sí le afectan). Se ignora a este superviviente cuando se dispara contra la zona en la que se encuentra.'),
    new Skill(49, 'Pistolero', 'El superviviente trata todas las armas de combate a distancia como si tuvieran el símbolo doble.'),
    new Skill(50, 'Provisiones', 'El superviviente puede llevar hasta 2 cartas de equipo adicionales. Estas cartas se colocan junto a su panel de control, pero se considera que las lleva en la mochila.'),
    new Skill(51, 'Provocación', 'El superviviente puede utilizar esta habilidad, sin coste, una vez en cada uno de sus turnos. Selecciona una zona situada como mucho a 2 zonas de distancia y hacia la que haya una ruta despejada (es decir, que no esté bloqueada por paredes ni puertas cerradas). No necesita línea de visión. Todos los zombis que se encuentren en la zona seleccionada reciben inmediatamente una activación adicional e intentarán alcanzar por todos los medios al superviviente que los provoca. Los zombis provocados ignoran al resto de supervivientes: no los atacarán, e incluso los pasarán de largo si fuera necesario para alcanzar al superviviente que los ha provocado.'),
    new Skill(52, 'Puede buscar más de una vez', 'El superviviente puede buscar varias veces en un mismo turno, gastando una acción por cada búsqueda.'),
    new Skill(53, 'Recarga gratuita', 'El superviviente puede recargar armas recargables (Escopeta de mamá, Recortada, etcétera) sin ningún coste.'),
    new Skill(54, 'Reflejos de combate', 'Cada vez que aparezcan zombis a alcance 0-1 (y antes de resolver cualquier posible avance impetuoso), el superviviente puede realizar inmediatamente una acción de combate gratuita contra ellos. Con esta acción se pueden eliminar más zombis de los que hayan aparecido. Las acciones de combate a distancia deberán dirigirse igualmente contra la zona en la que hayan aparecido los zombis. El superviviente puede utilizar esta habilidad una vez por cada carta de zombi que se robe.'),
    new Skill(55, 'Regeneración', 'Durante cada fase final, la vida del superviviente se restablece a su valor máximo.'),
    new Skill(56, 'Salto', 'El superviviente puede utilizar esta habilidad una vez en cada uno de sus turnos. Gastando 1 acción, puede moverse 2 zonas ignorando todo lo que haya en la zona intermedia (salvo paredes y puertas cerradas). Las habilidades relacionadas con el movimiento (como +1 zona de movimiento o Escurridizo) se ignoran, pero las penalizaciones al movimiento (como que haya zombis en la zona de inicio) se aplican.'),
    new Skill(57, 'Saqueador', 'El superviviente puede realizar acciones de búsqueda en cualquier zona de edificio y calle. Se aplican las reglas normales de búsqueda (por ejemplo, sigue sin ser posible buscar en zonas donde haya zombis).'),
    new Skill(58, 'Sed de sangre: [Acción]', 'El superviviente puede usar esta habilidad una vez en cada uno de sus turnos. Gastando 1 acción, podrá moverse un máximo de 2 zonas hasta una zona que contenga al menos 1 zombi. a continuación, obtiene 1 acción gratuita del tipo especificado (combate, cuerpo a cuerpo o a distancia). Se aplican las reglas de movimiento habituales.'),
    new Skill(59, 'Segador: [Acción]', 'Esta habilidad puede utilizarse cuando se asignen impactos al resolver una acción del tipo especificado (combate, cuerpo a cuerpo o a distancia). 1 de esos impactos puede eliminar gratuitamente a 1 zombi adicional del mismo tipo que esté en la misma zona. Con esta habilidad sólo se puede eliminar 1 único zombi adicional por cada acción. El superviviente obtiene la adrenalina otorgada por este zombi adicional.'),
    new Skill(60, 'Socorrista', 'El superviviente puede utilizar esta habilidad sin coste una vez en cada uno de sus turnos. Selecciona una zona que contenga al menos 1 zombi y 1 superviviente situada a alcance 1 de tu superviviente. Ambas zonas deben compartir línea de visión y una ruta despejada. Los supervivientes  de tu elección que estén en la zona seleccionada son arrastrados hasta la zona de tu superviviente sin penalizaciones. Esto no es una acción de movimiento. Un superviviente puede rechazar el rescate y quedarse en la zona seleccionada si su jugador así lo prefiere.'),
    new Skill(61, 'Superfuerza', 'El valor de daño de las armas de combate cuerpo a cuerpo de este superviviente es de 3.'),
    new Skill(62, 'Táctico', 'El turno del superviviente puede resolverse en cualquier momento de la fase de los jugadores, antes o después del turno de cualquier otro superviviente. Si varios supervivientes se benefician de esta habilidad al mismo tiempo, los jugadores pueden resolver sus turnos en el orden que prefieran.'),
    new Skill(63, 'Vínculo zombi', 'El superviviente juega un turno adicional cada vez que se roba una carta de activación adicional del mazo de zombis (pero no si se trata de un avance impetuoso). Este turno se resuelve antes que la activación adicional de los zombis. Si hay más de un superviviente con esta habilidad, los jugadores deciden el orden de juego de sus supervivientes.'),
  ];
}
